/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    'IMdi:check': typeof import('~icons/mdi/check')['default']
    'IMdi:contentCopy': typeof import('~icons/mdi/content-copy')['default']
    'IMdi:restore': typeof import('~icons/mdi/restore')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
